apiVersion: apps/v1
kind: Deployment

metadata:
  name: pod-validation-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-label-validation-deployment

  template:
    metadata:
      labels:
        app: pod-label-validation-deployment

    spec:
      containers:
      - name: validator
        image: "us-central1-docker.pkg.dev/csci-5409-w24/validator-docker/validator"
        imagePullPolicy: Always
        ports:
        - containerPort: 6001
        volumeMounts:
          - name: pod-label-storage-volume
            mountPath: /nisarg_PV_dir

      volumes:
      - name: pod-label-storage-volume
        persistentVolumeClaim:
          claimName: pod-label-volume-claim
