apiVersion: v1
kind: Service

metadata:
  name: validator-network-service

spec:
  selector:
    app: pod-label-validation-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6001