apiVersion: v1
kind: Service
metadata:
  name: calculator-network-service
spec:
  selector:
    app: pod-label-calculation-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6000
  type: loadBalancer
